# Generated by Django 4.1.5 on 2023-02-13 21:41

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, null=True)),
                ('second_name', models.CharField(default='', max_length=50, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('bio', models.TextField(default='', null=True)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2023, 2, 13, 23, 41, 22, 870531), null=True)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='main_image')),
                ('preview', cloudinary.models.CloudinaryField(max_length=255, verbose_name='preview')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2023, 2, 13, 23, 41, 22, 871531))),
                ('likes', models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('previews', cloudinary.models.CloudinaryField(max_length=255, verbose_name='previews')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='network_life.post')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_to', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
